// <auto-generated />
using System;
using Lis.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Lis.Persistence.Migrations
{
    [DbContext(typeof(LisDbContext))]
    [Migration("20260306072816_add_message_queued")]
    partial class add_message_queued
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lis.Persistence.Entities.ChatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<long?>("CurrentSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_session_id")
                        .HasJsonPropertyName("current_session_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id")
                        .HasJsonPropertyName("external_id");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_group")
                        .HasJsonPropertyName("is_group");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSessionId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("chat");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ContactEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("contact");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ContactIdentifierEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("channel")
                        .HasJsonPropertyName("channel");

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint")
                        .HasColumnName("contact_id")
                        .HasJsonPropertyName("contact_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id")
                        .HasJsonPropertyName("external_id");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("Channel", "ExternalId")
                        .IsUnique();

                    b.ToTable("contact_identifier");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.MemoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ContactId")
                        .HasColumnType("bigint")
                        .HasColumnName("contact_id")
                        .HasJsonPropertyName("contact_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasJsonPropertyName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("memory");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.MessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body")
                        .HasJsonPropertyName("body");

                    b.Property<int?>("CacheCreationTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cache_creation_tokens")
                        .HasJsonPropertyName("cache_creation_tokens");

                    b.Property<int?>("CacheReadTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cache_read_tokens")
                        .HasJsonPropertyName("cache_read_tokens");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id")
                        .HasJsonPropertyName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("external_id")
                        .HasJsonPropertyName("external_id");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens")
                        .HasJsonPropertyName("input_tokens");

                    b.Property<bool>("IsFromMe")
                        .HasColumnType("boolean")
                        .HasColumnName("is_from_me")
                        .HasJsonPropertyName("is_from_me");

                    b.Property<string>("MediaCaption")
                        .HasColumnType("text")
                        .HasColumnName("media_caption")
                        .HasJsonPropertyName("media_caption");

                    b.Property<string>("MediaType")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("media_type")
                        .HasJsonPropertyName("media_type");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens")
                        .HasJsonPropertyName("output_tokens");

                    b.Property<bool>("Queued")
                        .HasColumnType("boolean")
                        .HasColumnName("queued")
                        .HasJsonPropertyName("queued");

                    b.Property<string>("ReplyToId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("reply_to_id")
                        .HasJsonPropertyName("reply_to_id");

                    b.Property<string>("Role")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("role")
                        .HasJsonPropertyName("role");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sender_id")
                        .HasJsonPropertyName("sender_id");

                    b.Property<string>("SenderName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("sender_name")
                        .HasJsonPropertyName("sender_name");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id")
                        .HasJsonPropertyName("session_id");

                    b.Property<string>("SkContent")
                        .HasColumnType("jsonb")
                        .HasColumnName("sk_content")
                        .HasJsonPropertyName("sk_content");

                    b.Property<int?>("ThinkingTokens")
                        .HasColumnType("integer")
                        .HasColumnName("thinking_tokens")
                        .HasJsonPropertyName("thinking_tokens");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasJsonPropertyName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("\"external_id\" IS NOT NULL");

                    b.HasIndex("ChatId", "Timestamp");

                    b.HasIndex("SessionId", "Timestamp");

                    b.ToTable("message");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.PromptSectionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasJsonPropertyName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled")
                        .HasJsonPropertyName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasJsonPropertyName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("prompt_section");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.SessionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id")
                        .HasJsonPropertyName("chat_id");

                    b.Property<long>("ContextTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("context_tokens")
                        .HasJsonPropertyName("context_tokens");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<bool>("IsCompacting")
                        .HasColumnType("boolean")
                        .HasColumnName("is_compacting")
                        .HasJsonPropertyName("is_compacting");

                    b.Property<long?>("ParentSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_session_id")
                        .HasJsonPropertyName("parent_session_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary")
                        .HasJsonPropertyName("summary");

                    b.Property<Vector>("SummaryEmbedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("summary_embedding")
                        .HasJsonPropertyName("summary_embedding");

                    b.Property<long?>("ToolsPrunedThroughId")
                        .HasColumnType("bigint")
                        .HasColumnName("tools_pruned_through_id")
                        .HasJsonPropertyName("tools_pruned_through_id");

                    b.Property<long>("TotalCacheCreationTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_cache_creation_tokens")
                        .HasJsonPropertyName("total_cache_creation_tokens");

                    b.Property<long>("TotalCacheReadTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_cache_read_tokens")
                        .HasJsonPropertyName("total_cache_read_tokens");

                    b.Property<long>("TotalInputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_input_tokens")
                        .HasJsonPropertyName("total_input_tokens");

                    b.Property<long>("TotalOutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_output_tokens")
                        .HasJsonPropertyName("total_output_tokens");

                    b.Property<long>("TotalThinkingTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_thinking_tokens")
                        .HasJsonPropertyName("total_thinking_tokens");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ParentSessionId");

                    b.HasIndex("SummaryEmbedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SummaryEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SummaryEmbedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("session");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ChatEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.SessionEntity", "CurrentSession")
                        .WithMany()
                        .HasForeignKey("CurrentSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentSession");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ContactIdentifierEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.ContactEntity", "Contact")
                        .WithMany("Identifiers")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.MemoryEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.ContactEntity", "Contact")
                        .WithMany("Memories")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.MessageEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.ChatEntity", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lis.Persistence.Entities.SessionEntity", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.SessionEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.ChatEntity", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lis.Persistence.Entities.SessionEntity", "ParentSession")
                        .WithMany()
                        .HasForeignKey("ParentSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chat");

                    b.Navigation("ParentSession");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ChatEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ContactEntity", b =>
                {
                    b.Navigation("Identifiers");

                    b.Navigation("Memories");
                });
#pragma warning restore 612, 618
        }
    }
}
